baseURL = 'http://example.org/'
theme = "hugo-book"
languageCode = 'en-us'
title = 'PythonChalleges'
enableGitInfo = true

[params]
    BookTheme = 'auto'
    BookLogo ='logo.png'
    BookMenuBundle= '/menu'