baseURL = 'https://heartfelt-gecko-2c55b8.netlify.app/'
theme = "hugo-book"
languageCode = 'en-us'
title = "PythonChalleges"

[languages]
[languages.en]
  languageName = 'English'
  contentDir = 'content.en'
  weight = 1

[languages.es]
  languageName = 'Spanish'
  contentDir = 'content.es'
  weight = 2

[params]
    BookTheme = 'auto'
    BookLogo ='logo.png'
    BookMenuBundle= '/menu'
